version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo-data:/var/lib/mongodb
      - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASIC_AUTH_USERNAME=admin  # Set your desired username for authentication
      - ME_CONFIG_BASIC_AUTH_PASSWORD=password  # Set your desired password for authentication
    ports:
      - "8081:8081"  # Expose mongo-express on port 8081
    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongo-data:
